version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "RectorOrdersDatabase"
      POSTGRES_USER: "veglem"
      POSTGRES_PASSWORD: "1812"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - PSQL:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
volumes:
  PSQL:
    
